//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinect.Joy.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinect.Joy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _08___C {
            get {
                return ResourceManager.GetStream("_08___C", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _09___D {
            get {
                return ResourceManager.GetStream("_09___D", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _10___E {
            get {
                return ResourceManager.GetStream("_10___E", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _11___F {
            get {
                return ResourceManager.GetStream("_11___F", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _12___G {
            get {
                return ResourceManager.GetStream("_12___G", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _13___A {
            get {
                return ResourceManager.GetStream("_13___A", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _14___G__ {
            get {
                return ResourceManager.GetStream("_14___G__", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap full {
            get {
                object obj = ResourceManager.GetObject("full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Launch {
            get {
                object obj = ResourceManager.GetObject("Launch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pre {
            get {
                object obj = ResourceManager.GetObject("pre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream shutter {
            get {
                return ResourceManager.GetStream("shutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; root=&quot;rootRule&quot; tag-format=&quot;semantics/1.0-literals&quot; xmlns=&quot;http://www.w3.org/2001/06/grammar&quot;&gt;
        ///  &lt;rule id=&quot;rootRule&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;SHARE&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt; share &lt;/item&gt;
        ///          &lt;item&gt; share image &lt;/item&gt;
        ///          &lt;item&gt; share picture &lt;/item&gt;
        ///        &lt;/one-of&gt;
        ///      &lt;/item&gt;
        ///      
        ///      &lt;item&gt;
        ///        &lt;tag&gt;BACK&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt; back &lt;/item&gt;
        ///          &lt;item&gt; go back &lt;/item&gt;
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SpeechGrammar {
            get {
                return ResourceManager.GetString("SpeechGrammar", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tick {
            get {
                return ResourceManager.GetStream("tick", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap weibo {
            get {
                object obj = ResourceManager.GetObject("weibo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
